### ISSUE TITLE
Is it maintained?

### ISSUE THREAD

**Issue by ArmorDarks** [poppinss/indicative#105]
Hi!

This library has some interesting syntax solutions. However, looking at Pulse, I wonder is it still maintained?

**Comment by thetutlage** [comment]
Yes it is and since all the development is done, there is hardly anything else I can add to it

**Comment by ArmorDarks** [comment]
Thanks for reply

Hm, there seems to be 10 unresolved issues and some non-Greenkeeper PRs, so that made feeling of abandoned library...
