### ISSUE TITLE
Rule to restrict string to exact length

### ISSUE THREAD

**Issue by Andreyco** [poppinss/indicative#108]
If I am not mistaken, Laravel provides `size:n` rule to validate length of array and/or string.

Would be great to include such rule.

Open to PR?

**Comment by thetutlage** [comment]
Yup, also if you can add same to the raw validations aswell 👍

**Comment by Andreyco** [comment]
Gosh... totally forgot about this. Still on my list, will contribute later ;)

**Comment by thetutlage** [comment]
1.

**Comment by CodingDive** [comment]
Any news on this? :)
Edit: Oh I just saw the max and min rule. Don't need the size rule anymore.

**Comment by AleksandarSavic95** [comment]
For anyone coming from Google, You can use Laravel's [`'size:N'` rule](https://laravel.com/docs/5.3/validation#rule-size):
> For string data, value corresponds to the number of characters. For numeric data, value corresponds to a given integer value. For an array, size corresponds to the count of the array. For files, size corresponds to the file size in kilobytes.

Example: https://stackoverflow.com/a/56183514/2101117
