### ISSUE TITLE
Getting errors one field at a time, instead of a full array of them

### ISSUE THREAD

**Issue by anabellaspinelli** [poppinss/indicative#13]
Hi, I'm wondering if I'm doing something wrong here, or if Indicative is supposed to send errors one field at a time. My code is:

``` javascript
var schema = {
            title: 'required|min:10|max:100',
            description: 'required|min:30|max:300',
            seller: {
                name: 'required|min:3|max:30',
                email: 'required|email',
            }
 }
var messages = {
            required: 'Por favor ingresá {{ field }}',
            email: 'Por favor ingresá un email válido',
            number: 'Por favor ingresá sólo números en {{ field }}'
}

 Indicative.validate(schema, item, errorMessages).then(function (validation_passed) {
        itemModel.insert(item, function() {
            res.json({
                result: item
            });
        });
    }).catch(function (err) {
        console.log(err);
        res.json({
            error: err
     });
 });
```

So if the form is empty on Submit, I'm getting the error message just for title, and then when I complete that field and re-submit, then I get an error for the empty description, and so on. Is there any way to get them all at once?

Thank you!

PS: Sorry if my code is ugly, I'm a very newbie programmer :)

**Comment by thetutlage** [comment]
Use `validateAll` method instead of `validate`

**Comment by thetutlage** [comment]
Also as a quick tip you can use `dot` notation inside your scehma.

``` javascript
var schema = {
            title: 'required|min:10|max:100',
            description: 'required|min:30|max:300',
             'seller.name': 'required|min:3|max:30',
             'seller.email': 'required|email',
 }
```

This will remove unnecessary curly braces

**Comment by anabella-spinelli-olx** [comment]
Thank you!!

One more thing, is it possible to refer to the min and max values on custom error messages as with {{ field }} ?

Thanks again!

**Comment by thetutlage** [comment]
Yes checkout http://indicative.adonisjs.com/docs/node-validation-messages#templating

**Comment by anabellaspinelli** [comment]
Sorry, forgot to check if that was already in the docs. Thanks so much!
