### ISSUE TITLE
URL validation failing for short domains

### ISSUE THREAD

**Issue by tsriram** [poppinss/indicative#130]
URL validation is failing for short domains like `https://t.co` which is a valid URL. This is because the [regex](https://github.com/poppinss/indicative/blob/bd90485ad4cea1fa334f2a7f1e7019cf3345507c/src/Raw/index.js#L17) checks for a minimum of 2 characters for the domain name part. We've to probably change it to 1 I guess.

I can send a PR for that if you're okay.

**Comment by thetutlage** [comment]
Yup PR is welcomed
