### ISSUE TITLE
lodash's footprint in bundle size

### ISSUE THREAD

**Issue by Andreyco** [poppinss/indicative#140]
According to my measures, lodash's size is 526kb - pretty high.

I am sure, not every lodash's API are needed. Is it possible to reduce it's footprint in any way?

Similar to #126

**Comment by thetutlage** [comment]
Yup, PR is welcome

**Comment by Andreyco** [comment]
PR in progress...

**Comment by Andreyco** [comment]
To note, I have progress made on this. If accepted in near future, would love to have it released with other PR (momentjs removal) to keep possible (but not expected) breaking changes in single release.

**Comment by thetutlage** [comment]
Okay, so I have merged the `date-fns` PR.

I am thinking of having a separate branch with the frontend bundle logic in using `webpack` and then start changing the code.

This way we can track, how many bytes we are able to remove. What u think?

**Comment by Andreyco** [comment]
Thanks for merge, and yes. Please create dedicated branch.

**Comment by thetutlage** [comment]
Here's the first level build PR https://github.com/poppinss/indicative/pull/153
