### ISSUE TITLE
date_format with ISO 8601?

### ISSUE THREAD

**Issue by eliasisrael** [poppinss/indicative#142]
For the life of me, I can't get this to work. Is there some trick?

```js
const myRules = {
 "dateCreated": "required|date_format:YYYY-MM-ddTHH:mm:ss.SSSZ"
}
```

won't accept:

```js
{ "dateCreated": '2017-09-06T05:06:14.805Z' }
```

Someone, please explain my dain bramage to me.

**Comment by eliasisrael** [comment]
this version of the syntax from 3.0.0 doesn't appear to work either:

```
var indicative = require('indicative');

myRules = {
    "dateCreated":      [
        indicative.rule('date_format','YYYY-MM-ddTHH:mm:ss.SSSZ')
    ]
)
```

**Comment by thetutlage** [comment]
Will look into it now

**Comment by eliasisrael** [comment]
Apparently, I didn't have the moment() syntax correct. This works:

myRules = {
    "dateCreated":      [
        indicative.rule('date_format','YYYY-MM-DDTHH:mm:ss.SSSZ')
    ]
)

(note the 'DD')
As a convenience, having a couple of common date formats built into the validator might be a nice-to-have.

Something like:

var myRules = {
    "dateCreated": "required|date_ISO8601"
}

**Comment by Andreyco** [comment]
@eliasisrael you can create own validation rule exactly for this ;)

**Comment by thetutlage** [comment]
Yes, creating a custom rule makes more sense
