### ISSUE TITLE
Regex with char `|` not working

### ISSUE THREAD

**Issue by martin-badin** [poppinss/indicative#148]
Hello,

regex with char `|` inside regex not work. For example

/^(\+421|00420|0!00)[ ]?([0-9]{3})[ ]?([0-9]{3})[ ]?([0-9]{3})$/

Please your fix it. Thank you

**Comment by thetutlage** [comment]
You can make use of the `rule` method.
```js
const rule = require('indicative').rule

const rules = {
key: [rule('regex', /^(+421|00420|0!00)[ ]?([0-9]{3})[ ]?([0-9]{3})[ ]?([0-9]{3})$/)]
}
```

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
