### ISSUE TITLE
Rule 'alpha' doesn't allow non-english characters

### ISSUE THREAD

**Issue by gyszalai** [poppinss/indicative#15]
Failing example:

``` javascript
var rules = {name: 'required|alpha'};        
var stub = {"name":"Péter"};
```

**Comment by thetutlage** [comment]
This is normal behaviour as alpha allows [A-Z] only , you have to write custom rule for allowing french characters

**Comment by gyszalai** [comment]
Oh, thanks. I'll try writing a custom rule then.
