### ISSUE TITLE
pre-compiled version

### ISSUE THREAD

**Issue by protzi** [poppinss/indicative#152]
Hey, could you be so kind and provide pre-compiled ES5 version of this package. Cant build application with [create-react-app](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify)

**Comment by thetutlage** [comment]
There is a PR for that using rollup.

NOTE: This will not be the optimized version for the browsers, since we are bundling everything, in upcoming, I will be working to reduce the bundle size ( no dates yet )
