### ISSUE TITLE
Replace field with custom name on messages

### ISSUE THREAD

**Issue by mtamadon** [poppinss/indicative#156]
In laravel we can change fields name (laravel calls them attributes) with custom names on messages. 
ex.:
'attributes' => [
    'email' => 'E-mail address',
]
then the error message will be : "E-mail address is not right!"  I think it is better than "email is not right!"

I know that we can use custom messages (in laravel we have this option too) but I think creating custom name for fields is better than creating custom message for each validation rule.

Can we have this option on next version?

**Comment by thetutlage** [comment]
I am not in favor of this, it's like too many ways to do one thing, which often leaves people why this and why that.

Also in real world apps, you will have to define custom messages, no matter what.
