### ISSUE TITLE
number rule pass NaN

### ISSUE THREAD

**Issue by mohamed-hendawy** [poppinss/indicative#158]
good job to dd number rule but it pass if value is NaN

**Comment by RomainLanz** [comment]
Hey @mohamed-hendawy! 👋 

Could you please provide a failing test?

**Comment by mohamed-hendawy** [comment]
let object: any = { key: 'a' };
            object.key = +object.key; // here key is NaN
          
            let Rules = {
                key: 'required|number'
            }
            await indicative.validateAll(object, Rules);

validation pass now

**Comment by thetutlage** [comment]
Should be good with new release. `4.0.x`

**Comment by mohamed-hendawy** [comment]
Thanks :D
