### ISSUE TITLE
Can't install on OS X

### ISSUE THREAD

**Issue by rikumalminiemi** [poppinss/indicative#16]
When installing on OS X I get the following error:
npm ERR! indicative@1.2.4 install: `node ./node_modules/coffee-script/bin/coffee -c .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the indicative@1.2.4 install script 'node ./node_modules/coffee-script/bin/coffee -c .'.
npm ERR! This is most likely a problem with the indicative package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/coffee-script/bin/coffee -c .

It seems that npm can't find coffee-script module. The search path is "Project root/node_modules/indicative/node_modules/coffee-script/bin/coffee".

**Comment by thetutlage** [comment]
interesting, i am on mac itself but let me check

**Comment by thprapav** [comment]
same error on El Capitan using homebrew:

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/4.1.1/bin/node" "/Users/username/.node/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.5
npm ERR! code ELIFECYCLE

npm ERR! indicative@1.2.4 install: `node ./node_modules/coffee-script/bin/coffee -c .`
npm ERR! Exit status 1
npm ERR!

**Comment by thetutlage** [comment]
Fixed as of `v1.2.5`

**Comment by rikumalminiemi** [comment]
Thank you very much, it's working perfectly now!

**Comment by thprapav** [comment]
:+1:  Thank you!
