### ISSUE TITLE
date_format is broken in 3.0.6

### ISSUE THREAD

**Issue by eliasisrael** [poppinss/indicative#160]
This used to work prior to 3.0.6, but now it fails when validating legit values:

`    "dateCreated": [
        indicative.rule('date_format', 'YYYY-MM-DDTHH:mm:ss.SSSZ')
    ],`

**Comment by thetutlage** [comment]
Can u share the value that is failing the validation

**Comment by eliasisrael** [comment]
The value of dateCreated that was rejected came from this JSON

`{ "userId": "d3fff782-785e-4281-8c48-33e1ed7fe0af", "name": "big buck bunny", "mimeType": "video/mp4", "width": 1280, "height": 720, "storage": "http://sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4", "duration": "15.01", "dateCreated": "2017-12-24T19:33:53.231Z", "lastUpdated": "2017-12-24T19:33:53.231Z", "id": "5fe665f0-e8e1-11e7-8095-e1c2f5073280" }`

**Comment by thetutlage** [comment]
The `Z` keyword is the timezone and when indicative parses the date it converts `Z` to whatever timezone your server is on. 

Internally it uses https://date-fns.org/v1.29.0/docs/format

**Comment by eliasisrael** [comment]
In ISO8601 dates, the Z indicates zulu timezone, i.e. GMT+0000. It's defined in the spec as such.

The way the dateFormat validator is coded now, it is rejecting a valid ISO8601 date because it's attempting to reformat the date using date-fns.

If I were to change the requested format in dateFormat to quote the 'Z' with [Z], then date-fns would change the timezone to local and the result STILL wouldn't match. Reformatting the date introduces all kinds of uncertainty like that.

Alas, it appears that date-fns doesn't handle UTC dates at all, or at least not very well. Pity.

**Comment by thetutlage** [comment]
Yes you are right but still they are 2 things to it.

1. Formatting a date and then doing a comparison is wrong ( I will fix it )
2. Also you are expecting the `Z` to be matched as string, whereas you must provide a value for it.

So as per me

`2017-12-24T19:33:53.231+05:00` or `2017-12-24T19:33:53.231+<any-time-zone>` should work fine.

**Comment by eliasisrael** [comment]
I don't have that option. I'm validating for insertion into DynamoDB, which expects the Z.

Also, Z is a valid timezone, per the ISO8601 spec. See the summary here:

http://www.cl.cam.ac.uk/~mgk25/iso-time.html#zone

> Without any further additions, a date and time as written above is assumed to be in some local time zone. In order to indicate that a time is measured in Universal Time (UTC), you can append a capital letter Z to a time as in
> 23:59:59Z or 2359Z
> Note: The Z stands for the “zero meridian”, which goes through Greenwich in London, and it is also commonly used in radio communication where it is pronounced “Zulu” (the word for Z in the international radio alphabet). Universal Time (sometimes also called “Zulu Time”) was called Greenwich Mean Time (GMT) before 1972, however this term should no longer be used. Since the introduction of an international atomic time scale, almost all existing civil time zones are now related to UTC, which is slightly different from the old and now unused GMT.]

**Comment by thetutlage** [comment]
What do you think of this implementation? 

Also this will be available in version `4.0.x`, which will be release soon

**Comment by eliasisrael** [comment]
Thanks for the quick fix! I made a couple of comments on that revision, which I hope you can see. In brief: there's a typo in the comment: Z equals UTC or GMT+0000 (not +0100), and I would recommend adding a test for the ISO8601 format with fractional seconds included.

**Comment by thetutlage** [comment]
Done

**Comment by thetutlage** [comment]
Added to the docs too https://epic-albattani-83fe42.netlify.com/docs/dateformat

**Comment by eliasisrael** [comment]
Thanks!
