### ISSUE TITLE
Provide es modules build

### ISSUE THREAD

**Issue by vladshcherbin** [poppinss/indicative#168]
Currently, `umd` format is used. Since you are using rollup, it'll be great if `es` output format would be added for possible tree-shaking optimisations.

**Comment by thetutlage** [comment]
100%, is there any convention that everyone agree on. Like rollup uses the `module` field from `package.json` file to use the es6 module ( if exists ). Is it same for webpack?

**Comment by vladshcherbin** [comment]
@thetutlage yes, according to [docs](https://webpack.js.org/configuration/resolve/#resolve-mainfields) `module` field is resolved before `main` if exists.

**Comment by thetutlage** [comment]
Cool, lemme add it

**Comment by thetutlage** [comment]
Want to try it from Github and lemme know if all works fine.

I tried creating a simple example and build size dropped from `32KB -> 10KB`. But feel free to share if more optimizations can be done. ( I am not much active with build tools these days )

**Comment by vladshcherbin** [comment]
@thetutlage I believe the format should be set to `es` instead of `cjs` for es modules.

**Comment by RomainLanz** [comment]
Yes, also no need to uglify and minify the bundle.

**Comment by thetutlage** [comment]
Closing, since the newer releases are not focused on browsers anymore
