### ISSUE TITLE
Pre-compiled ES5 Version

### ISSUE THREAD

**Issue by jrock17** [poppinss/indicative#177]
I'm trying to use Indicative with create-react-app but getting minify errors.

After searching, it looks like you've added this via rollup. But I'm not sure how to use to install the version I need.

Is there a way to get the pre-complied version version requested here: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

Thanks!

**Comment by thetutlage** [comment]
Sure! Lemme look into this

**Comment by mhemrg** [comment]
Same issue here.
The `main.js` file contains `let` and `const` keywords. With the current Babel config, it doesn't transpile them to ES5 and `creact-react-app` requires ES5.
