### ISSUE TITLE
number and integer should probably cast to integer like boolean and date?

### ISSUE THREAD

**Issue by jcassee** [poppinss/indicative#178]
The `boolean` and `date` validations accept string representations, but the `number` and `integer` validations do not. This feels like a failure of symmetry, and makes it a bit more awkward to validate query parameters in Adonis.

**Comment by thetutlage** [comment]
Yup, it should. Mind sharing a PR for same?

**Comment by OnyekaIjeh** [comment]
I have this issue. Number and integer validation failing on correct number inputs because they're actually strings in the request.

**Comment by jcassee** [comment]
Thanks, @thetutlage!
