### ISSUE TITLE
How to write a custom Method Regex validation

### ISSUE THREAD

**Issue by mathiesha** [poppinss/indicative#18]
Hi sorry if I am being obviously stupid, can you point in the direction of how to write a custom Regex validation? example validation should contain Alphanumeric and special characters.

**Comment by Sicria** [comment]
+1

I really want to be able to do something like this.

```
_id: "required|regex:'^[0-9a-fA-F]{24}$'"
```

**Comment by thetutlage** [comment]
Will add support for custom regex

**Comment by thetutlage** [comment]
Added as of `v1.2.7`

**Comment by thetutlage** [comment]
Make sure to use it without quotes.

## Use it this way

```
_id: "required|regex:^[0-9a-fA-F]{24}$"
```

Docs here http://indicative.adonisjs.com/docs/regex-validation-rules#regex

**Comment by Sicria** [comment]
Thank you, much appreciated!

**Comment by mathiesha** [comment]
Wow great thanks
