### ISSUE TITLE
Validation fails with fails()==true but messages()==[] after updating p-series dependency to 1.1.0

### ISSUE THREAD

**Issue by CherryDT** [poppinss/indicative#180]
We noticed that after an `npm update` our form validations started failing in a strange way - we were redirected back to the form but without any errors.

Further investigation showed that `validation.fails()` is truthy, but `validation.messages()` is an empty array, which was puzzling.

Now, after enabling breaking on caught exceptions in the debugger, we caught this exception:
```
Expected task to be a `Function`, received `Promise`
```

Unfortunately I no longer have the stack trace right now but it is thrown in `node_modules/p-series/index.js` at line 12, and the cause in your module is `src/Validation/engine.js` line 39 in which you call `pSeries(validationMap)` and `validationMap` contains promises instead of functions.

This error is unfortunately swallowed because you disregard the actual error in your catch block and instead assume that it is always an validation failure - but since it wasn't, no error message was pushed!

Now, the immediate cause of this is the input validation that `p-series` add in their update to 1.1.0 recently. See [this commit](https://github.com/sindresorhus/p-series/pull/2/commits/693125cd0b721f6da27d463c0b9b71ba1618b9ea) from https://github.com/sindresorhus/p-series/pull/2.

What's puzzling me is that it worked before, because if I see this right, `runValidationOnField` will always return a promise, and `p-series` stuffs it into a `.then(...)`. And some quick tests of mine showed that a `.then(...)` with something that is not a function (e.g. a number, a promise, a string) will simply do nothing (also not alter the result value of the previous promise).

As a workaround, I added this code to my application, which seems to have fixed the problem:
```
{
  const _ = require('lodash')
  const pSettle = require('p-settle')
  const pSeries = require('p-series')
  const ValidationEngine = require('indicative/src/Validator/engine')
  ValidationEngine.validateField = function (data, field, validations, messages, formatter, runAll) {
    const validationsMap = _.map(validations, (validation) => {
      return () => ValidationEngine.runValidationOnField(data, field, validation.name, messages, validation.args, formatter)
    })
    return runAll ? pSettle(validationsMap) : function () {
      return pSeries(validationsMap)
    }
  }
}
```
The essence here is the addition of `() =>` before `ValidationEngine.runValidationOnField`.

EDIT: Looking at your code, this may not be an issue with the current version. However, we are currently using Adonis 4.0 and while maybe this would be solved with Adonis 4.1, we cannot update the framework right now, and an "npm update" should not break anything. Therefore I would ask you to release an update for your previous major version in which this issue is fixed (by either changing the semver selector in the p-series dependency or fixing the issue in the code, the latter of course being preferred). Thank you!

**Comment by thetutlage** [comment]
Can you share from which version to which version, you upgrade the `indicative` or `@adonisjs/validator` package?

**Comment by CherryDT** [comment]
These didn't upgrade, I believe. During `npm update`, a dependency of `indicative` - `p-series` - was updated from 1.0.0 to 1.1.0.

EDIT:
```
└─┬ @adonisjs/validator@4.0.9
  └── indicative@3.0.6
```

Would it possible for you to do a release `indicative@3.0.7` where you change the semver for `p-series` from `^1.0.0` to `1.0.0` (or `~1.0.0`) to prevent the upgrade to `1.1.0`?

**Comment by thetutlage** [comment]
Not sure if it's still required, but I don't have much bandwidth for back porting changes.

**Comment by taviroquai** [comment]
I just got into this problem too.

A new clone of my app, after npm install, validator stopped working as expected.
Thanks to @CherryDT a dowgrade to p-series seems to fixed the problem.
