### ISSUE TITLE
indicative.extend not working???

### ISSUE THREAD

**Issue by smiley05** [poppinss/indicative#181]
Hi, Thank you for your great work and support.

When I tried the sample as shown per the docs Iam getting **"time is not defined as a validation rule"**. Please help
the following is the sample I tried. Please correct whats wrong?
var indicative = require('indicative');
const timeRegex = /([01]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?/

const timeFn = function (data, field, message, args, get) {
  return new Promise((resolve, reject) => {
    const fieldValue = get(data, field)

    if (fieldValue && !timeRegex.test(fieldValue)) {
      return reject(message)
    }

    resolve('validation passed')
  })
}
indicative.time = timeFn;
rules = {
        first_name: 'required',
	last_name: 'required',
        time:    'required|time'
    }

**Comment by thetutlage** [comment]
First, please format your message properly. It's hard to understand. 

Also have you considered the docs? https://indicative.adonisjs.com/docs/api/extend

**Comment by smiley05** [comment]
Well thank you for your response. Yes, I followed the docs and tried the same example indicative.time=timeFn, but when I set time in the rules setting as shown, I am getting "time is not defined as a validation rule" error. 
rules = {
time: 'required | time'
}

**Comment by thetutlage** [comment]
Can you point me to the docs which say that you can define rules on the `indicative` object?

**Comment by smiley05** [comment]
I mean from this docs sample only -  https://indicative.adonisjs.com/docs/api/extend

**Comment by thetutlage** [comment]
As per the docs you have to use the `validations` object and not `indicative`

```js
const { validations } = require('indicative')
validations.time = timeFn
```

**Comment by smiley05** [comment]
oh yes!!!  I didn't understood before, now I got it. Thank you.
