### ISSUE TITLE
Regex fails when using :

### ISSUE THREAD

**Issue by eNzyOfficial** [poppinss/indicative#182]
Hey,

I had a quick look and saw there was an issue opened and closed as fixed. However I seem to be still getting the same problem.

```js
return {
  slug: 'required|regex:/^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$/'
}
```

Returns `Invalid flags supplied to RegExp constructor '-[a-zA-Z0-9]+)*$/'`

(On a side note, I am aware that there is the `slug` sanitizer, but I would like to check the db for uniqueness before hand, plus, it seems to add dashes between numbers, regardless of where they are, eg. `h3ll0-w0rld` would become `h-3-ll-0-w-0-rld` rather than `h3ll0-w0rld`)

**Comment by thetutlage** [comment]
If you will go through the docs, under `Syntax guide`, it talks about the limitations of the syntax https://indicative.adonisjs.com/docs/syntax-guide#_limitations

What you need is to use the `rule` function over a string.

```js
slug:  [
  rule('required'),
  rule('regex', '/^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$/')
]
```

**Comment by eNzyOfficial** [comment]
When I had a look through the adonis docs I couldn't find anything about using rule(), could you point me in the right direction?

**Comment by thetutlage** [comment]
I believe it will be same

```js
const { rule } = use('Validator')
```

**Comment by eNzyOfficial** [comment]
Awesome, thanks!
