### ISSUE TITLE
Range validation bug when using `rule`

### ISSUE THREAD

**Issue by FerrielMelarpis** [poppinss/indicative#184]
#### Description
indicative returns `ENGINE_EXCEPTION` error when using `rule` to construct `range` validation

#### Code for reproducing the issue
```js
const {
    validate,
    rule
} = require('indicative');

const rules = {
    a: 'required',
    // this works
    // b: 'required|range:0,5'
    b: [
        rule('required'),
        rule('range', [0, 5])  // this doesn't work
    ]
};

const data = {
    a: 1,
    b: 1
};

validate(data, rules)
    .then(console.log)
    .catch(console.error)
```

#### Investigation
- This is probably because of the fact that I used Number instead of string for the rule parameters.
  - Using `rule('range', ['0', '5'])` works as expected since '0' is truthy.
- This line might have been the issue: https://github.com/poppinss/indicative/blob/75c981a5b1f47c70965fa4c57d8d3a26975a86f8/src/validations/range.js#L25
  - I think there should be a type check like this:
    ```js
    if (Number.isNaN(Number(min)) || Number.isNan(Number(max))) {
        ...
    ```
- Not sure if this kind of issue also occurs for some validations

**Comment by thetutlage** [comment]
Yup, mind creating a PR for same?

**Comment by FerrielMelarpis** [comment]
@thetutlage I submitted #185. I added some test cases to catch the issue. Please check if there's something wrong with my code. Thanks!

**Comment by thetutlage** [comment]
Fixed in related PR
