### ISSUE TITLE
Invalid documentation on toBoolean sanitization 

### ISSUE THREAD

**Issue by FrenchMajesty** [poppinss/indicative#188]
Hello,

On the following page: https://indicative.adonisjs.com/docs/toboolean

The code snippets use `boolean` as a sanitization but it is incorrect. I tried to use it but I got an error saying `boolean is not a sanitization rule` so looking at the rest of the documentation I used `to_boolean` instead since it was consistent with the other rules and it did work.

It would be nice if someone could correct that small mistake in the doc.

**Comment by RomainLanz** [comment]
Hey @FrenchMajesty! 👋 

Could you make a PR for this?
