### ISSUE TITLE
trim() sanitizer?

### ISSUE THREAD

**Issue by moltar** [poppinss/indicative#189]
I think a `trim` sanitizer would be useful to remove extra whitespace. What do you think?

**Comment by thetutlage** [comment]
Yes, happy to add with options to remove from `left`, `right` or all whitespaces

**Comment by moltar** [comment]
Do you want to add it or do you want a PR?

**Comment by RomainLanz** [comment]
PR would be awesome! 👍

**Comment by pelevesque** [comment]
Done. https://github.com/poppinss/indicative/pull/191
