### ISSUE TITLE
dateFormat: Can't ensures date is valid when using 'DD/MM/YYYY' as a format

### ISSUE THREAD

**Issue by pellizzetti** [poppinss/indicative#195]
## Problem

Using ``dateFormat:DD/MM/YYYY`` as rule will always fail validation.

## Behavior

If I make a request with the following data:
```js
console.log(request.input('birthday'))
// 02/05/1963
```
Using this rule:
```js
const rules = {
  birthday: 'required|dateFormat:DD/MM/YYYY'
}
```
The validation fails. I think that happens because ``raw/dateFormat.js`` -> ``date-fns/format`` is receiving a String has first parameter. Passing a Date object return the right date/format:

```js
const stringFmt = dateFns.format('02/05/1963', 'DD/MM/YYYY')
const dateFmt = dateFns.format(new Date(1963, 4, 2), 'DD/MM/YYYY')

console.log(stringFmt)  // 05/02/1963
console.log(dateFmt)    // 02/05/1963
```
[JSFiddle link](https://jsfiddle.net/2jvdrmxn/1/)

## Specifications

  - **Node**: 8.5.0
  - **npm**: 5.6.0
  - **adonisjs/validator**: "^5.0.3"

**Comment by thetutlage** [comment]
This is directly a shortcoming of Javascript and really hard to write a workaround for.

If you pass the raw string to the `new Date` function, it does swap the month with the date, since that is the default format for Javascript.

```js
new Date('02/05/1963')
// Tue Feb 05 1963 00:00:00 GMT+0530 (India Standard Time)
```

Do u have any suggestions?

**Comment by pellizzetti** [comment]
> This is directly a shortcoming of Javascript and really hard to write a workaround for.

I did not know that (I'm somewhat new to the JS ecosystem) but, yeah, I thought it wouldn't be an easy task.

> Do u have any suggestions?

Not at the moment, sorry. But next month, when I have more free time, I can give some attention to the subject and try to get some solutions.

**Comment by thetutlage** [comment]
Sure, I will keep this issue opened and see if I can find something solid around it

**Comment by thetutlage** [comment]
After looking into multiple ways, I hardly think, there is any way to work around this issue. If you are still looking for a solution, then feel free to open the issue and discuss ways around it

**Comment by MarcosGin** [comment]
Hi, I'm using Adonis.js, and I'm having the same problem, any news about this?

**Comment by radiumrasheed** [comment]
Anyone else found a workaround for this?
