### ISSUE TITLE
Accepted accepts null and empty strings.

### ISSUE THREAD

**Issue by rapodaca** [poppinss/indicative#197]
Using 5.0.5 and this schema:

    const schema = { 'foo': 'accepted' }

Validation passes for:

    const test = { foo: '' }

and

    const test = { foo: null }

Documentation says:

> Ensures that the field under validation is accepted. Empty strings, false, null, 0 and undefined values will be considered as not accepted.

https://indicative.adonisjs.com/docs/accepted

False and 0 are rejected as expected.

**Comment by thetutlage** [comment]
Is `const schema = { 'foo', 'accepted' }` this the correct schema syntax?

**Comment by thetutlage** [comment]
Closing since not actionable and no answer from the issue reporter
