### ISSUE TITLE
Incorrect documentation on custom Formatter

### ISSUE THREAD

**Issue by rapodaca** [poppinss/indicative#198]
Documentation gives [this template](https://indicative.adonisjs.com/docs/formatters) for a custom formatter:

    class MyFormatter {
      constructor () {
        this.errors = []
      }

      addError (error, field, validation, args) {
        let message = error

        if (error instanceof Error) {
          validation = 'ENGINE_EXCEPTION'
          message = error.message
        }

        this.errors.push({ field, validation, message, args })
      }

      toJSON () {
        return this.errors
      }
    }

However, using this template will result in a thrown validation error even if all constraints are satisfied.

The source for [VanillaValidator](https://github.com/poppinss/indicative/blob/develop/src/formatters/Vanilla.js) revealed the problem. `toJSON` needs to return `null` if there are no errors. Apparently, the framework uses the output of this method to determine if any errors are present. If null is returned, then there are no errors.

Therefore, one way to address the issue would be to update the documentation as follows:

      // must return null if no errors are present
      toJSON () {
        return this.errors.length ? this.errors : null
      }

**Comment by thetutlage** [comment]
Yes, you are write, we should update the docs to reflect this. Mind creating a PR for same?
