### ISSUE TITLE
IP validation passing incorrectly

### ISSUE THREAD

**Issue by Sicria** [poppinss/indicative#20]
I'm not sure if I'm doing this correctly but for some reason, this passes.

```
Indicative
    .validate({ip: 'required|ip'}, {ip: 'H'})
    .then(function(passed) {
        console.log('passed');
    })
    .catch(function(err) {
        console.log(err);
    });
```

**Comment by thetutlage** [comment]
Yes this is not the ideal behavior, i have raised an issue https://github.com/arasatasaygin/is.js/issues/156
as indicative uses `is.js` under the hood for certain validations.

**Comment by smithb1994** [comment]
@thetutlage You might want to consider migrating to validator.js instead of is.js... Validator is well maintained, and I'm not too sure about is.js... https://github.com/chriso/validator.js

**Comment by thetutlage** [comment]
leave it as i have written raw validator from stratch and will be launching new version in few hours, working on docs

**Comment by thetutlage** [comment]
removed `is.js` as of `v2`
