### ISSUE TITLE
Tailwind .font-mono not being applied properly

### ISSUE THREAD

**Issue by mattijsbliek** [poppinss/indicative#201]
I see the mono font stack being applied [here](https://github.com/poppinss/indicative/blob/develop/static/_site/public/style.css), but the compiled CSS just contains the `font-family: operatormono`. If that isn’t installed on your machine, all code examples look like this:

![image](https://user-images.githubusercontent.com/2960795/44087562-8ae07bec-9fc0-11e8-8e5d-3d8eeea784de.png)

I’m not familiar with Tailwind, so I’m not sure why this isn’t working exactly.

**Comment by RomainLanz** [comment]
It probably hasn't been published yet.

I'm pretty sure @thetutlage will do it in a while 👍
