### ISSUE TITLE
'equals' validator not able to handle booleans

### ISSUE THREAD

**Issue by Aljendro** [poppinss/indicative#209]
The 'equals' validator is not able to validate boolean values. Always validates to false and returns error.

## Package version
5.0.8

## Node.js and npm version
node: 8.10
npm: 6.5.0

## Sample Code (to reproduce the issue)
validate({ val: false }, { val: [ rule('equals', false) ]}); // throws error

**Comment by thetutlage** [comment]
The newer version fixes this issue and here is a test case for same https://github.com/poppinss/indicative-rules/commit/8181e1829057d453bbb577306fc06afd3403bbfd#diff-ea3975cbc35ce1eed69d5822445f4b6aR61
