### ISSUE TITLE
Unable to use custom regex validation

### ISSUE THREAD

**Issue by mathiesha** [poppinss/indicative#21]
Tried using the below pattern to validate

[a-zA-Z0-9\-~!@#$%^*()_+{}:|""?`;',./[]<>&]+

Unhandled rejection TypeError: Cannot read property 'call' of undefined

**Comment by thetutlage** [comment]
You can show the entire code ?

**Comment by mathiesha** [comment]
Hey sorry for not being descriptive the code is as follows

```
     var values = {
        firstName: req.body['firstName'],
        lastName: req.body['lastName'],
        email: req.body['email'],
        password: req.body['password']
            };

    var rules = {
        firstName: 'required|alpha',
        lastName: 'required|alpha',
        email: 'required|email',
        password: 'required|regex:[a-zA-Z0-9\\\-~!@#$%^*()_+{}:|""?`;',./[\]<>&]+'
    }

    var feilds = {
        firstName: values['firstName'],
        lastName: values['lastName'],
        email: values['email'],
        password: values['password']
    }

    indicative.validateAll(rules, feilds).then(function (success) {
        res.json({"Message": "Success"});
    }).catch(function (errors) {
        res.json(errors);
    });
```

Hope it is me who is doing something wrong. Thanks

**Comment by thetutlage** [comment]
Are you using `v1.2.7` ? Make sure to remove indicative from node_modules and then re-install it.

```
npm install indicative@latest --save
```

**Comment by thetutlage** [comment]
Okay not your mistake, parser splits rules with `|` and your regex includes one. Let me fix it

**Comment by thetutlage** [comment]
For regex especially where you have `|` symbol ,  you have to define rules as an array. So in your case it will be

``` javascript
password: ['required','regex:[a-zA-Z0-9\\\-~!@#$%^*()_+{}:|""?`;\',./[\]<>&]+']
```

Also update indicative to `v1.2.8`

**Comment by mathiesha** [comment]
Sorry for the late reply. thanks for this
