### ISSUE TITLE
Working on an Indicative React Hook!

### ISSUE THREAD

**Issue by marceloadsj** [poppinss/indicative#210]
Hey bros. Sorry to send here, I didn't found a better channel!

@thetutlage if you want to delete this issue, np!

I'm working on a React Hook integration with this awesome library:
https://www.npmjs.com/package/react-indicative-hooks

It's on the beginning but, well, I think will be really good to use together with React.

:-)

**Comment by thetutlage** [comment]
Looks nice 😄
