### ISSUE TITLE
Are you using Indicative on browser?

### ISSUE THREAD

**Issue by thetutlage** [poppinss/indicative#213]
Indicative works on Browsers and Node.js both. However, maintaining the browser version comes with extra tasks like:

1. Monitoring the build size.
2. Offering multiple types of builds based upon user requirements.
3. Cross browser testing

Ofcourse, all the above mentioned are doable, however, if no one is using Indicative on browser, then I would like to save myself some time.

Please let me know if you are using it on browsers or not. If I don't get any replies for a month, then I will consider dropping the support

**Comment by marceloadsj** [comment]
I've built a react hooks package based on it:
https://github.com/marceloadsj/react-indicative-hooks

I can help with the browser support to keep it up and running!

**Comment by thetutlage** [comment]
Nice! I am planning to move it to typescript. Do you think you can help me with following:

1. Create and test builds for different browsers ( high priority )
2. Have smaller/different builds like lodash.

**Comment by marceloadsj** [comment]
Sure! The 'lodash approach' would be nice.
I can focus on this two things, create the supported browser list and after, split the build into smaller pkgs.
Soon I send you some PRs!

**Comment by thetutlage** [comment]
@marceloadsj Just wait. I am working the typescript migration stuff right now. I will give you the heads up once done 😄

**Comment by marceloadsj** [comment]
Haha, okay! :smile:

**Comment by thetutlage** [comment]
Released https://github.com/poppinss/indicative/releases/tag/v7.2.0. Feel free to open a new issue if someone is interested in adding browser support. I am short on time, sorry :(
