### ISSUE TITLE
new rules "default" to set default value

### ISSUE THREAD

**Issue by fas3r** [poppinss/indicative#215]
Hello, 

## Why this feature is required (specific use-cases will be appreciated)?
Create a new rule "default" that would set a "default value" if the field is missing in the data set or if empty. 

As some field in database have already a default value that can be replaced, it could be good to have the same behaviour in indicative.

## Have you tried any other work arounds?
To fill the empty/missing field in the data set that need to be validate, I  merge the "data" to verify with a template that contains default value. 
```
import { _merge } from ...

const data = {
   field1 : 'value1',
   field2 : 'value2',
   field3 : ''
}

const template = {
   field1 : '',
   field2 : '',
   field3 : 0,
   field4 : 'public'
}

const dataMerged = _merge({}, template, data);

console.log(dataMerged);
{
   field1 : 'value1',
   field2 : 'value2',
   field3 : 0,
   field4 : 'public'
}


... then executing validation on dataMerged;

```
## Are you willing to work on it with little guidance?
Yes no problem.

Thanks for this great plugins. 
Fas3r.

**Comment by thetutlage** [comment]
Validation rules are not meant to set default values. Sorry, this is out of the scope of the library
