### ISSUE TITLE
Integer/number validation rule not working as expected for array items

### ISSUE THREAD

**Issue by hlozancic** [poppinss/indicative#217]
Number validation rule will not fail if you have undefined or null inside array.
And integer validation rule will not fail if you have undefined, false or null inside array.

## Package version
5.0.8

## Node.js and npm version
node: 11.6.0  
npm: 6.50

## Sample Code (to reproduce the issue)
```
const {validate} = use('Validator')

const example1 = {someArray: [undefined, null]}
const validate1 = await validate(example1, {someArray: 'array', 'someArray.*': 'number'})
console.log(validate1.fails()) // should be true... instead gives false

const example2 = {someArray: [false, undefined, null]}
const validate2 = await validate(example2, {someArray: 'array', 'someArray.*': 'integer'})
console.log(validate2.fails()) // should be true... instead gives false
```

**Comment by thetutlage** [comment]
You need to use `required` to validate non-existing values. Every validation method is created in a way to test only existing values, which makes them flexible to be used with optional values as well.

So it has to be

```js
{someArray: 'required|array', 'someArray.*': 'required|number'})
```

**Comment by hlozancic** [comment]
Yeah,  but what if you want this behaviour (if empty array is valid input):

```
const example3 = {someArray: []}
const validate3 = await validate(example3, {someArray: 'array', 'someArray.*': 'required|integer'})
console.log(validate3.fails()) // should be false... instead gives true
```

So, it's not possible to have this logic? I want user to be able to send empty array or if he is sending items inside, items must be integers.
