### ISSUE TITLE
validator:In fails on integers

### ISSUE THREAD

**Issue by pixelpaulaus** [poppinss/indicative#218]
when validating an integer is one of...
`required|integer|in:18451,18367,18364`
It returns a fail as it is matching against a string. The submitted value is indeed a integer tho.
validator:equals works, but not validator:In

**Comment by thetutlage** [comment]
Yup coz `in:18451,18367,18364` is interpreted as string. You have to use the `rule` method here.

```js
{
  code: [
    rule('required'),
    rule('integer'),
    rule('in', [18451,18367,18364])
  ]
}
```

**Comment by pixelpaulaus** [comment]
hmmm, not sure that is possible in adonisjs :-(

shouldn't it see the interger requirement and match against integers?

**Comment by thetutlage** [comment]
Why you think it's not possible in Adonis?

**Comment by pixelpaulaus** [comment]
sorry i could not find any example of writing in the rule method you mentioned.
so i could rewrite...

`
const rules = {
      subject: 'required|string|max:200',
      department: 'required|integer|in:18451,18367,18364',
      service: 'integer',
    }
`

to be like...

`
const rules = {
      subject: 'required|string|max:200',
      department: code: [
                                       rule('required'),
                                           rule('integer'),
                                          rule('in', [18451,18367,18364])
                                         ],
      service: 'integer',
    }
`

**Comment by thetutlage** [comment]
You can use it as follows:

```js
const { rule } = use('Validator')
```

**Comment by pixelpaulaus** [comment]
thanks, but that is not very clear. are there any examples in the docs to do it this way?

`const validation = await validate(request.post(), rules)`

**Comment by thetutlage** [comment]
Indicative docs does talk about it https://indicative.adonisjs.com/docs/syntax-guide#_limitations
