### ISSUE TITLE
multiple validation return "too many errors"

### ISSUE THREAD

**Issue by amelon** [poppinss/indicative#22]
On my use case at least.

With following code

``` javascript
var indicative = new(require('indicative'));

var stub      = {
    email       : ''
  };

var schema   = {
    email:  'required|email'
  };

//first call
 indicative
    .validateAll(schema, stub)
    .then(function(success){
      console.log('success', success);
    })
    .catch(function(errors){
      console.log('error', errors);
    });
//second call
 indicative
    .validateAll(schema, stub)
    .then(function(success){
      console.log('success', success);
    })
    .catch(function(errors){
      console.log('error', errors);
    });
```

I expect result

``` javascript
// for first validation
error [ { field: 'email',
    message: 'required validation failed on email',
    rule: 'required' } ]

// for second validation
error [ { field: 'email',
    message: 'required validation failed on email',
    rule: 'required' } ]
```

But I get this result

``` javascript
// for first validation
error [ { field: 'email',
    message: 'required validation failed on email',
    rule: 'required' },
  { field: 'email',
    message: 'required validation failed on email',
    rule: 'required' } ]

// for second validation
error [ { field: 'email',
    message: 'required validation failed on email',
    rule: 'required' },
  { field: 'email',
    message: 'required validation failed on email',
    rule: 'required' } ]
```

As you can see errors for both validation is returned on each result.

**Comment by thetutlage** [comment]
`validateAll` is an async function and re-running the function before completing the first one will not give parser the chance to clear off things.

Here you can do couple of things.

``` javascript

indicative
.validateAll(schema, stub)
.then(function () {
  return indicative.validateAll(schema,stub)
})
.then(function(success){
  console.log('success', success);
})
.catch(function(errors){
  console.log('error', errors);
});
```

Or have 2 instances of indicative

``` javascript
var indicative = new(require('indicative'));
var indicative1 = new(require('indicative'));
```

**Comment by amelon** [comment]
I think the problem is the single stack error.

You should have a new instance for each `validateAll` call and not a singleton.

As far as I understand, indicative is also a singleton (the same for Error class).

``` coffee
class Validator extends RULES

  'is': IS

  # singleton instance holder
  instance = null

  constructor: ->
    if !instance then instance = this
    super()
    return instance

```

Thus I have no chance to have multiple instance of Indicative.

In fact my use case is to validate rows

``` javascript
Promise.map(rows, function(row) {
 return myIndicative.validateAll(row, myRules)
  .then(function() {// my row is ok})
  .catch(function(err) { //report error on row })
})
.then(function() { // blabla })
```

Is it possible to make classes (Validator, Error, Messages) not singleton?

**Comment by thetutlage** [comment]
Even not being singleton will not help , coz you will be using same instance of `indicative` to have multiple validations running parallely not in sequence.

**Comment by thetutlage** [comment]
Ideal situation will be to make an array of rows and then validate them, having validation inside a loop will is not good choice

**Comment by amelon** [comment]
In node, you may have erratic problem by sharing the same state for multiple call.

I think my exemple is a simulation of simultaneous users calling validateAll at the same time.

To solve this, in `validateField`, you don't need Error class (maybe for formatting).
Just reject the error (without pushing it in the stack)

In `validateAll`, you could instanciate a new Error class.

**Comment by thetutlage** [comment]
Can you have a pull request for same , i am happy to merge it as long as it passes all the tests

**Comment by amelon** [comment]
oups... actually i never write coffescript.

I can try, let me check what I can do

**Comment by thetutlage** [comment]
What about writing in Javascript itself, i will manage the CoffeeScript part before merge

**Comment by amelon** [comment]
I made a pull request here: https://github.com/Adonis-Js/indicative/pull/23

**Comment by thetutlage** [comment]
Merged as of `v1.2.9` , thanks for your efforts :+1:

**Comment by thetutlage** [comment]
Added you to the contributors list

**Comment by amelon** [comment]
thanks ;)
