### ISSUE TITLE
escape replace word

### ISSUE THREAD

**Issue by wmtamit** [poppinss/indicative#222]
if i try to use  escape in name and i write the name like this s>?bi so give me a result like this S Gt Bi .

**Comment by thetutlage** [comment]
What should be the output?

**Comment by wmtamit** [comment]
output :-  s?bi 
in [indicative](https://indicative.adonisjs.com/docs/escape) doc give  escape remove <,> but my cash it don't give output like this

**Comment by thetutlage** [comment]
Can you share the exact code. I think you are also using the `slug` sanitization rule and that is converting `>` to `GT`

**Comment by wmtamit** [comment]
```
get sanitizationRules () {
    return {
      name: 'trim|escape',
      number: 'trim|escape',
      swift_code: 'trim|escape',
      email: 'normalize_email|escape',
      primary_contact_no: 'trim|escape',
      secondary_contact_no: 'trim|escape',
      fax_no: 'trim|escape',
      ...addressValidation.sanitizationRules
    }
}
```

i use escape like this

**Comment by thetutlage** [comment]
Added a test for same in the newer version and seems to be working as expected. https://github.com/poppinss/indicative-rules/commit/937733dcff63e5cc20382ceda145c9873e036734
