### ISSUE TITLE
toNumber sanitizer

### ISSUE THREAD

**Issue by padinko** [poppinss/indicative#223]
## Why this feature is required (specific use-cases will be appreciated)?
API can get real number, I need to Number.parseFloat() in controller instead of validator like in toInt sanitizer

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
