### ISSUE TITLE
email is not exported by  'indicative/builds/validations'

### ISSUE THREAD

**Issue by ansarizafar** [poppinss/indicative#224]
I am trying to import email and other validations like this
```
  import {   email,   required,   min,   max } from 'indicative/builds/validations'
```
but I am getting this error "email is not exported by  'indicative/builds/validations'"
Please help me to resolve this issue.

**Comment by thetutlage** [comment]
Not supported in newer release at all https://github.com/poppinss/indicative/releases/tag/v7.2.0
