### ISSUE TITLE
Bug Adonisjs Indicative: dateFormat:'YYYY-MM-DD HH:mm:ss' always invalid

### ISSUE THREAD

**Issue by begueradj** [poppinss/indicative#226]
## Problem
`dateFormat:'YYYY-MM-DD HH:mm:ss'` never gets validated unless I remove `HH:mm:ss` or keep only: `YYYY-MM-DD HH`.

The exact error message I see in the console:

> dateFormat validation failed on effective_datetime

## Sample code
```javascript
get rules () {
  return {
    name: 'required',
    effective_datetime: 'required|date|dateFormat:YYYY-MM-DD HH:mm:ss'
  }
}
```
## Package version
Current

## Node.js and npm version
npm: 6.9.0
Node.js: 11.8.0
AdonisJs: 4.1.0

## BONUS (a sample repo to reproduce the issue)
[Link](https://github.com/begueradj/indicative-dateformat)

**Comment by RomainLanz** [comment]
Hey @begueradj! 👋 

This rule is well tested: https://github.com/poppinss/indicative/blob/develop/test/node/validations.spec.js#L421

If you believe there's a bug, could you please create a test case that fail?

**Comment by begueradj** [comment]
There is at least [this test ](https://github.com/poppinss/indicative/blob/develop/test/node/validations.spec.js#L537)that covers this case. However the demo I shared shows there is a problem with `dateFormat()`. Actually this was asked as a question on the forum, this means an other user stumbled on the exact same issue

**Comment by webNeat** [comment]
The [Limitations section in the docs](https://indicative.adonisjs.com/docs/syntax-guide#_limitations) says:
> Since the validation rules are defined using a string based expression, it has certain limitations. You cannot use reserved keywords like `:` or a `|`, within arguments.

So you should rewrite your code as
```js
const {rule} = use('Validator')

//...
  get rules() {
    return {
      name: 'required',
      effective_datetime: [
        rule('required'),
        rule('date'),
        rule('dateFormat', 'YYYY-MM-DD HH:mm:ss')
      ]
    }
  }
```

**Comment by begueradj** [comment]
I read that section but I guess I did not take it seriously. I did not try your solution but I believe it will work. Thank you very much for the feedback. I will try it ASAP. @webNeat

**Comment by LukasChiama** [comment]
> The [Limitations section in the docs](https://indicative.adonisjs.com/docs/syntax-guide#_limitations) says:
> 
> > Since the validation rules are defined using a string based expression, it has certain limitations. You cannot use reserved keywords like `:` or a `|`, within arguments.
> 
> So you should rewrite your code as
> 
> ```js
> const {rule} = use('Validator')
> 
> //...
>   get rules() {
>     return {
>       name: 'required',
>       effective_datetime: [
>         rule('required'),
>         rule('date'),
>         rule('dateFormat', 'YYYY-MM-DD HH:mm:ss')
>       ]
>     }
>   }
> ```

This does not work when timezone is added
