### ISSUE TITLE
TypeError: isObject is not a function

### ISSUE THREAD

**Issue by jean-smaug** [poppinss/indicative#244]
👋 I'm just trying the hello world in a Vue.js app and i get this error. 
I didn't find any informations in issues or on your forum :/

```
TypeError: isObject is not a function
    at ValidationsRunner.exec (ValidationsRunner.js?52fc:57)
    at Executor.exec (Executor.js?66bb:17)
    at exports.validate (index.js?f1e2:22)
    at eval (request.js?b775:17)
    at Module../src/utils/request.js (app.js:10453)
    at __webpack_require__ (app.js:724)
    at fn (app.js:101)
    at eval (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/Poll.vue?vue&type=script&lang=js&:15)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/Poll.vue?vue&type=script&lang=js& (app.js:2775)
    at __webpack_require__ (app.js:724)
```

## Package version
7.2.0

## Node.js and npm version
Node : 10.16.0
Yarn : 1.16.0

## Sample Code (to reproduce the issue)

```js
const schema = {
  username: "required|alpha",
  password: "required|min:4|max:40"
};

const data = {
  username: "virk",
  password: "supersecret"
};

validate(data, schema)
  .then(console.log)
  .catch(console.error);
```

**Comment by thetutlage** [comment]
Hello 👋. Indicative is written for Node.js

**Comment by jean-smaug** [comment]
😮 
![image](https://user-images.githubusercontent.com/22884251/61213303-f003cf00-a704-11e9-88aa-68f2b4de60ce.png)

**Comment by thetutlage** [comment]
Hahah! My bad, used the old banner, will fix

**Comment by webNeat** [comment]
Hello @thetutlage 
I see that this error comes from the `indicative-compiler` due to the way it imports the `isobject` package.
Can I make a PR if I can fix it for the browser? it would really be awesome if this library can be used on the client side :)

**Comment by thetutlage** [comment]
@webNeat I believe, it's more than fixing one or two odd errors. I am happy to receive contributions, if someone can own the browser side of things. Which may include

1. Making sure all packages works fine with browser (with test cases)
2. Monitoring package size.
3. Making `indicative-rules` work with tree shaking

**Comment by mathieutu** [comment]
Yeah, running into this issue too, and was planning to use Indicative to handle automatic front validation from the rules I have in Laravel, so I really really think that it should be a great idea to allow Indicative to run on browser!

**Comment by thetutlage** [comment]
Happy to accept contributions

**Comment by iowayfarer** [comment]
Just an FYI, if you're using Webpack for nodejs stuff (lambda in my case) then this issue also comes up.

**Comment by parker-codes** [comment]
I just ran into this as well thinking that it was for browsers as well. I understand the extra work to support browsers, but still hopeful.

**Comment by TayyebaShoaib** [comment]
Is there any fix for this? Should I use the older version of the library?

**Comment by thetutlage** [comment]
Use the old version, as this version is not meant for browsers
