### ISSUE TITLE
message: "lowerCase is not a sanitization method"

### ISSUE THREAD

**Issue by woodgates** [poppinss/indicative#249]
I'm getting the following error when trying to use lower_case sanitization in my adonisjs validator:
message: "lowerCase is not a sanitization method"
name: "Error"
status: 500

## Package version
5.0.6

## Sample Code (to reproduce the issue)
adonisjs Update Validator:
OfferUpdate.js
class OfferUpdate {

  get sanitizationRules () {
    return {
      summary: 'strip_tags',
      tags:'lower_case'
    }
  }  

  get data () {
    const requestBody = this.ctx.request.all()
    const userId = this.ctx.params.userId
    return Object.assign({}, requestBody, { userId })
  }  
}

**Comment by olaoluwa-98** [comment]
@thetutlage I am also getting this error

**Comment by thetutlage** [comment]
@olaoluwa-98 Can you share which version of Indicative you are using? Also `5.0.6` doesn't have this sanitization rule. Here's the docs to the older version https://indicative-v5.adonisjs.com/

**Comment by olaoluwa-98** [comment]
I am using `@adonisjs/validator` version `5.0.6` which has `indicative version 5.0.8` as a dependency

**Comment by thetutlage** [comment]
Yup, so as said, the `lowerCase` sanitization is part of the newer version, not the one AdonisJs is using.
