### ISSUE TITLE
required rule for integer=0

### ISSUE THREAD

**Issue by amir-s** [poppinss/indicative#27]
Hi,

Assume I use the following rule for the `amount` property: `required|integer`.

`amount` is integer and it is ok to be zero, but if set to zero, it is not going to be validated by `required` rule.

indicative utilized `is.truthy`, but `is.truthy` explicitly rejects the number values equal to zero:

```
is.truthy = function(value) {
    return is.existy(value) && value !== false && is.not.nan(value) && value !== "" && value !== 0;
};
```

**Comment by thetutlage** [comment]
Fixed as of `v1.3.1`

**Comment by amir-s** [comment]
@thetutlage Perfect :+1: 
Thanks, and keep up the great work!

**Comment by thetutlage** [comment]
Thanks :)
