### ISSUE TITLE
Regex rule example in the documentation is incorrect

### ISSUE THREAD

**Issue by gyszalai** [poppinss/indicative#29]
The example in the documentation of the regex rule is as follows:

```
'regex:/^[(]{0,1}[0-9]{3}[)]{0,1}[-\s\.]{0,1}[0-9]{3}[-\s\.]{0,1}[0-9]{4}$/'
```

however it doesn't work this way. The correct way is the following:

```
'regex:^[(]{0,1}[0-9]{3}[)]{0,1}[-\s\.]{0,1}[0-9]{3}[-\s\.]{0,1}[0-9]{4}$'
```

that is, the slashes at the beginning and the end of the regex is not necessary.

**Comment by thetutlage** [comment]
yeah my bad, will update docs

**Comment by tomerb15** [comment]
just spent 2 hours on this :)

**Comment by thetutlage** [comment]
done as of `v2.0.0`
