### ISSUE TITLE
how can i validate positive integers including 0?

### ISSUE THREAD

**Issue by tomerb15** [poppinss/indicative#32]
I can't get 0 to pass.

**Comment by tomerb15** [comment]
never mind, forgot to parseInt it.

**Comment by ozziest** [comment]
I think that we need that feature and also negative rule. 

For example;

```js
import { validations } from 'indicative/validator'
 
const rules = {
  amount: 'number|positive',
  expense: 'number|negative'
}
```

They can be very cool features. What do you think, @thetutlage?
