### ISSUE TITLE
Even if validation is passed, it takes me to error callback

### ISSUE THREAD

**Issue by bron10** [poppinss/indicative#37]
Here is my code,

```
function validateData(res){
    var schema = {
        username: 'required'
    };

    var data = {
        username: "foobar"
    };
 indicative.validate(schema, data)
.then(function(success){
        // Validation passed
        res.send("in success");              
    })
    .catch(function(errors){
        console.log("in errrors");
        // Validation failed
        res.send(errors);
    });       
}
```

Let me know if something is mistaken form my side

**Comment by thetutlage** [comment]
Yes, you need to pass `data` as first argument and `schema` as 2nd. Checkout breaking changes on documentation http://indicative.adonisjs.com/docs/2.0/upgrade#breaking-changes

**Comment by bron10** [comment]
ok thankx :), Hope you update here too http://indicative.adonisjs.com/docs/2.0/basics#validate-rules-data-messages-  creates confusion
