### ISSUE TITLE
Problem updating to new structure

### ISSUE THREAD

**Issue by samundrak** [poppinss/indicative#38]
I have used this module and there was lib folder where in message.js i have modified as my need but when i am updating module .. the whole structure is changed and i cant find lib folder can i get older structure code

**Comment by thetutlage** [comment]
Why do you need to change the actual code? you can define your custom messages http://indicative.adonisjs.com/docs/2.0/basics#custom-messages

**Comment by samundrak** [comment]
Sorry for that .. i have changed the actual code because of my need .. as i want messages as array on error and string on success .. so can i get old codes?

**Comment by samundrak** [comment]
I have forked and modified branch 27 .. and compiled the coffee script .. Thanks for your time
