### ISSUE TITLE
Nested schema

### ISSUE THREAD

**Issue by jeremieca** [poppinss/indicative#45]
Hello,

I have two questions : 

First, is it possible to validate nested arrays like : 
    {
        name: "hello",
        friends: [{ userId: 12, age: 23 }, { userId: 13, age: 25 }]
    }

I would like to validate objects in friends array...

Second, is it a way to embeded schema ? For instance : 
     {
        name: "required",
        friends: ["Friend"]
    }

Where "Friend" refers to another indicative schema called Friend.

Thanks for taking time to answer and sorry for my bad english, I'm french :)
Jérémie.

**Comment by thetutlage** [comment]
Nope there is no support for same
