### ISSUE TITLE
Schema rule 'above' works incorrectly

### ISSUE THREAD

**Issue by Donnyofdoom** [poppinss/indicative#54]
Given "above:0.5", the following output are returned:

-1 -> fail (expected)
0 -> fail (expected)
0.5 -> fail (expected)
0.7 -> fail (UNEXPECTED)
1 -> pass (expected)
1.7 -> pass (expected)

Seems to be interpreting the argument as an integer and then performing the greater than check.

**Comment by thetutlage** [comment]
Cannot reproduce it, would be great if you can have some failing tests for same

**Comment by Donnyofdoom** [comment]
Here's a paste of some test code. Note: It also happens without the required or number params

http://pastebin.com/rhZHax5t

Output:

> > [ { field: 'amount',
> >     message: 'amount must be greater than 0.5',
> >     rule: 'above' } ]

PS This is after running "npm uninstall indicative" and "npm i --save indicative".

> npm uninstall indicative  
> unbuild indicative@1.3.1                                                                                      
> 
> npm i --save indicative  
> npm WARN package.json node_server@1.0.0 No description  
> npm WARN package.json node_server@1.0.0 No repository field.  
> npm WARN package.json node_server@1.0.0 No README data  
> |  
> indicative@1.3.1 postinstall C:\wsserver\node_server\node_modules\indicative  
> coffee -c .                                                                                                 

indicative@1.3.1 node_modules\indicative  
├── async@0.9.2  
├── is_js@0.7.6  
├── coffee-script@1.10.0  
├── bluebird@2.10.2  
├── moment@2.11.2  
├── lodash@3.10.1  
└── dot-object@0.11.0 (commander@2.9.0, glob@5.0.15)

**Comment by thetutlage** [comment]
cannot reproduce
