### ISSUE TITLE
Remove restriction on the `args` length

### ISSUE THREAD

**Issue by m4nuC** [poppinss/indicative#55]
Is there any reason for:

`validation = matchedValidation.splice(0, 1)` in `_parseValidation`

I'd need more than one argument in a certain use case.

**Comment by thetutlage** [comment]
can u explain the use case?

**Comment by m4nuC** [comment]
Its a for an existence check, I have 2 scenarios that would need to use arguments. 
1- Checking a nested document. For instance I have a `phone_number` nested document and I need to check that `phone_number.number` does not already exist.

2- In some cases I need to specify which collection need to be used. (i.e. I have a temporary collection that hold stuff that will be validated later)

I could use one validator for all these cases if I had access to more than one argument.

**Comment by thetutlage** [comment]
Okay its hard for me to imagine it. Can you share some data sample and what exactly you would like to do with it.

For example

``` javascript
const data = {
   phone_number: {
      number: '91029102999'
   }
}
```

**Comment by m4nuC** [comment]
Here is what the validator looks like:

``` javascript
var unique = async function (data, field, message, args, get) {
  return new Promise ((resolve, reject) =>  {
    let value = get(data, field);

    if (! field) throw new error('No field was specified for unique checks');
    if (! value) reject(`${field} is required`);


    // If args then change collection
    const collec = args[0] ? this.db.collection(args[0]) : this.collection;

    return collec.findOne({[field]: value})
      .then(res => {

        if (res === null) {
          return resolve('validation passed');
        }

        if (res._id) {
          value = value.number|| value;
          return reject(`${value} is already in use`)
        }

        return reject(`${value} is already in use`)
      })
      .catch(() => {
        throw new error('There was an error when checking for duplicates');
      });
  })
}
```

As you can see here i am using args to change the collection. But now in some instance I would also need to specify a key at where data is located in a subdocument. Let's say I am checking the `number` in the `phone_number` sub doc:

```
const data = {
   phone_number: {
      number: '91029102999'
   }
}
```

Overall is there a reason for limiting the number of argument ? Right now if I pass:
`somevalidator:arg1:arg2`, then argument received will be `arg1:arg2`. It open the door to silent bugs. Either throw a warning for any attempt to mach more than one argument or allow as many arguments as are passed.

**Comment by thetutlage** [comment]
I believe you can do it with `unique:arg1,arg2`. Here is the documentation for same http://indicative.adonisjs.com/#indicative-basics-rules

**Comment by m4nuC** [comment]
That does work. Thanks!
