### ISSUE TITLE
Example request

### ISSUE THREAD

**Issue by jjshoe** [poppinss/indicative#56]
Can you provide an example of validating with both the schema and raw validations? For example, validating both a name and telephone number.

**Comment by thetutlage** [comment]
Check docs please http://indicative.adonisjs.com/

**Comment by jjshoe** [comment]
That's where I started, but wasn't understanding how to combine them. There's no single example that combines both that I can see.

**Comment by thetutlage** [comment]
Ideally there is no need to combine them.
What exactly you are trying to achieve? A real example with code will help.

**Comment by jjshoe** [comment]
The particular use case I have in mind is specifying a way to validate an object which is then turned into a resume. Ideally this could all be specified in a schema file which could be included, but validations like phone are only available as a raw validation. 

I'm not understanding how I would possibly combine the raw validations with schema, is there any way to represent a raw validation in the schema?

The following doesn't work, because phone isn't valid in schema:

```
ValidateObject.prototype.validateFileObject = function() {
  var schema = {
    name: 'required|alpha_numeric',
    email: 'required|email',
    phone: 'required|phone'
  };

  var data = this.fileObject.getFileObject();

  indicative
  .validateAll(data, schema)
  .then(function () {
    // validation passed
    console.log('success');
  })
  .catch(function (errors) {
    // validation failed
    console.log(errors);
  });
}
```

**Comment by thetutlage** [comment]
What you need is to extend the schema validator and add `phone` rule to it. Here are the docs http://indicative.adonisjs.com/#indicative-extending-extending-schema-validator
