### ISSUE TITLE
Regex min max length matches not working

### ISSUE THREAD

**Issue by dhesson** [poppinss/indicative#57]
Using indicative@2.0.6 in node.

I am trying to match phone numbers via regex, with my regex stating that I want at least 10 digits or more.

Schema

```
const schema = {
    phone: "regex:^\\d{10,}$"
};
```

Data

```
const data = {
    phone: "1234567890"
};
```

Expected: `then` invocation; no errors.

Actual: `catch` is invoked, with errors.

If I remove the `,}` from the regex, the validation passes.  If I put in a range cap, such as `{10,20}`, the validation fails.

Here is some code I used for sanity check and validated the data above fine:

```
const regex = /^\d{10,}$/
regex.test(data.phone); // -> true
```

**Comment by thetutlage** [comment]
The parser splits your regex definition by splitting it with `,`.

I will add an alternative way to define regex rules with some quick tests. Most probably it will be something like below.

``` javascript
const schema = {
    phone: {
      regex: {args: ['^\\d{10,}$']}
    }
};
```

**Comment by thetutlage** [comment]
Fixed in https://github.com/poppinss/indicative/commit/26468ac2bbab6b521a764f52ac14edc560d1357e.


Docs will be out soon
