### ISSUE TITLE
Regex for decimal number check not working

### ISSUE THREAD

**Issue by bron10** [poppinss/indicative#58]
Using indicative@2.0.6, got error `Invalid flags supplied to RegExp constructor '2})?$'`, while working on following:

``` javascript
var rule = {
 decimal : ['regex:^[0-9]+(.[0-9]{1,2})?$'] 
};
```

``` javascript
var data = {
decimal : 12.12
};
```

Thankx in advance..

**Comment by thetutlage** [comment]
It is a known issue. Indicative rules parser will break the regex. I am working to fix it.

**Comment by thetutlage** [comment]
Closing as this is related to #57
