### ISSUE TITLE
support global / extend message

### ISSUE THREAD

**Issue by whcmark** [poppinss/indicative#59]
Problem: If we wanna change default message, each time have to pass `message` value 

```
indicative.validate(rules, schema, messages)
```

could do something just like indicative.extend:

```
indicative.message()
```

**Comment by thetutlage** [comment]
@devmark Indicative does not maintain any state, so `messages` object needs to be passed everytime. If you want you can wrap `indicative.validate` inside your own method and let that method remove the usage of `messages` everytime.
