### ISSUE TITLE
Sanitization in Schema

### ISSUE THREAD

**Issue by Sljux** [poppinss/indicative#64]
A lot of validation libraries support sanitization in schema. Are you planning to add this feature? A use case would be:

``` javascript
let data = {
    number : '25'
};
let rules = {
    number : 'to_int|min:10|max:45'
};

indicative.validate(data, rules);
```

**Comment by thetutlage** [comment]
This is wrong fundamentally.
1. How a method called `validate` can do sanitization? It's name says validate.
2. Sanitization returns a new object with sanitized data, which will be wrong fundamentally if `validate` will return a new object. 

Validation methods are supposed to run a set of rules and throw error when a set of rules fails. Whereas sanitization loops over the object to return a transformed object.

**Comment by Sljux** [comment]
Valid point :)

**Comment by thetutlage** [comment]
Closing the issue, please feel free to create another if you have any specific questions
