### ISSUE TITLE
Is there a way to use a generator function instead of promise when extending the schema validation?

### ISSUE THREAD

**Issue by chanlito** [poppinss/indicative#68]
If there's way please leave some tips or hints for me.

**Comment by thetutlage** [comment]
You can wrap your generator function inside `co.wrap` and return it https://www.npmjs.com/package/co

**Comment by chanlito** [comment]
![screenshot from 2016-09-14 13 46 51](https://cloud.githubusercontent.com/assets/15667259/18502536/d34d440c-7a81-11e6-8205-a2f2cab81842.png)

Is this good enough?
