### ISSUE TITLE
equals validation problem with numbers

### ISSUE THREAD

**Issue by helnokaly** [poppinss/indicative#69]
The equals validation fails with numbers because it compares Number with String (1 === '1')

``` js
data: {
  num: 1
}
```

``` js
rules: {
  num: 'integer|equals:1'
}
```

``` js
validation:  {
  "errors": [
    {
      "field": "num",
      "validation": "equals",
      "message": "equals validation failed on num"
    }
  ]
}
```

**Comment by thetutlage** [comment]
Sorry for the late reply have been busy lately. I will cast the value to a number before running the validation. Thanks for reporting.
