### ISSUE TITLE
schema regex and OR directive

### ISSUE THREAD

**Issue by zerr0s** [poppinss/indicative#82]
Hi, forgive me for my bad english.

The "or" directive in my regex is not working:
`"type": "['regex:^search1|search2|search3$']",`
The pipe seems to be interpreted by the indicative engine and return:
`"search2 is not defined as a validation"`

Is there another way to do this ?

**Comment by thetutlage** [comment]
Fixed in https://github.com/poppinss/indicative/commit/26468ac2bbab6b521a764f52ac14edc560d1357e.


Docs will be out soon
