### ISSUE TITLE
500 error in docs

### ISSUE THREAD

**Issue by Zolmeister** [poppinss/indicative#9]
This page gives me a 500 error:
http://indicative.adonisjs.com/docs/03-rules/array

Was looking for docs on validating nested structures e.g. `Joi.array().items(Joi.number())`

**Comment by thetutlage** [comment]
Will fix docs links , as there are more heading towards 500.

Indicative does not handle nested structures as of now , but if you can give me a complete example of how you are expecting to validate nested rules. I will be more than happy to work on same

**Comment by Zolmeister** [comment]
We currently use Joi to validate incoming API requests like so:
https://github.com/claydotio/hyperplane/blob/master/controllers/event.coffee#L44
And our schemas - https://github.com/claydotio/hyperplane/blob/master/schemas.coffee

These may contain nested structures

**Comment by thetutlage** [comment]
Ok make sense , so you have nested schema and may be looking for something like below

``` javascript
tags:{
  event: 'required'
},
person:{
  firstname: 'required'
  email:    'required|email'
}
```

**Comment by thetutlage** [comment]
added support for nested objects as of v1.1.1

## Example

``` javascript



var indicative    =  new(require("indicative"));

var rules = {
  "person.firstname" : "required",
  "person.profile.email" : "required|email"
}

var stub = {
  person:{
    firstname: "somename",
    profile:{
     email: "someone"
   }
  }
};

var messages = {
  "person.profile.email.email" : "Email should be valid "
}


indicative.validate(rules,stub,messages)
.then(function(success){
  console.log('success>>>',success);
})
.catch(function(error){
  console.log('error>>>',error);
})


```
