### ISSUE TITLE
Allow making every field required by default

### ISSUE THREAD

**Issue by rightaway** [poppinss/indicative#98]
I am setting every field to `required`, but if I miss setting it on one field I wouldn't realize it. If there would be a way to make every field required by default, and I can specify `optional` for the ones that don't need to be there, then it would make things more robust.

**Comment by thetutlage** [comment]
That is not possible and it is better to be explicit with validation rules, otherwise how on the earth someone can tell which all fields are validated, since data payload can have anything.
